#!/bin/zsh

sudo -v

brew cleanup -s
brew prune
brew cask cleanup

npm cache -g clear
rm -rf ~/.npm
rm -rf ~/.node-gyp

# clear Mail.app downloaded attachments
rm -rf ~/Library/Containers/com.apple.mail/Data/Library/Mail\ Downloads/*

# CCleaner
open /Applications/CCleaner.app
