#!/bin/zsh

sudo -v

brew cleanup -s
brew prune

npm cache -g clear
rm -rf ~/.npm
rm -rf ~/.node-gyp

sudo gem cleanup -q

# rebuild ZSH completion index
rm -f ~/.zcompdump
compinit

# clear Mail.app downloaded attachments
rm -rf ~/Library/Containers/com.apple.mail/Data/Library/Mail\ Downloads/*

# CCleaner
open /Applications/CCleaner.app
